### ISSUE TITLE
TypeError: * wants int - metric_module.py

### ISSUE THREAD

**Issue by molnarszilard** [whynotw/YOLO_metric#3]
I wanted to use this method by calling 'python3 modulized/compare_simple.py', but I have got an error:
'TypeError: * wants int' 
for file 'modulized/module/metric_module.py' in the line 234:
"content2 += "%*sPrediction\n"%(12+(len(content2)-10)/2,"")"
The problem can be that '12+(len(content2)-10)/2' is not necessarily an integer.
My solution is to rewrite line 234 to:
"content2 += "%*sPrediction\n"%(round(12+(len(content2)-10)/2),"")"

But there could be other solutions as well

**Comment by ghost** [comment]
Hi @molnarszilard  guy how you do datasetting..? all those .txt path.. i am not getting how to set? can  you please tell me?

**Comment by molnarszilard** [comment]
Hi @lrscse, the .txt paths are created when preparing to train a new dataset.
I have achieved them by following the methods written in:
https://medium.com/@manivannan_data/how-to-train-yolov3-to-detect-custom-objects-ccbcafeb13d2
from this site there is another link to:
https://medium.com/@manivannan_data/how-to-train-yolov2-to-detect-custom-objects-9010df784f36
carefully follow these steps, and you should be able to create your files.

**Comment by ghost** [comment]
Hi @molnarszilard  i have  ground truth and detction result ( confidence score and cordinates of predicted box) then how i will prepare for calculating mAP ?
and possibly confusion matrix.. i am getting error

**Comment by molnarszilard** [comment]
I have modified in modulized/compare_simple.py the following paths to match my files DIRNAME_TEST (9), DIRNAME_PREDICTION (10), FILENAME_GROUNDTRUTH (11).
Unfortunately, I have only briefly worked with this, and since then, I have moved onto other things, so I do not remember exactly what I had there, but I suggest that think about it, and experiment. (or ask the owner of the code, it is possible that you have other problems than I had, and I cannot help solving those)
